export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_COLLEAGUES_PENDING = 'REQUEST_COLLEAGUES_PENDING';
export const REQUEST_COLLEAGUES_FAILURE = 'REQUEST_COLLEAGUES_FAILURE';
export const REQUEST_COLLEAGUES_SUCCESS = 'REQUEST_COLLEAGUES_SUCCESS';